#!/bin/sh
for arg in "$@"; do url="$arg"; done
case "$url" in
  *raw.githubusercontent.com*package.json) printf '%s\n' '{"version":"1.3.0"}' ;;
  *raw.githubusercontent.com*marketplace.json)
    printf '%s\n' '{"plugins":[{"name":"rogue-build-scenario","version":"2.0.0"},{"name":"rogue-plugin-dev","version":"1.1.0"},{"name":"rogue-curriculum-builder","version":"2.0.0"},{"name":"rogue-active-deployment","version":"2.0.0"}]}' ;;
  *api.github.com*releases/latest) printf '%s\n' '{"tag_name":"v1.3.0","body":"### Added\n- Auto-update notifier.\n\n### Fixed\n- Various stability improvements."}' ;;
  *) exit 1 ;;
esac
