#!/bin/sh
for arg in "$@"; do url="$arg"; done
case "$url" in
  *raw.githubusercontent.com*package.json) echo '{"version":"1.2.1"}' ;;
  *raw.githubusercontent.com*marketplace.json)
    echo '{"plugins":[{"name":"rogue-build-scenario","version":"2.0.0"},{"name":"rogue-plugin-dev","version":"1.1.0"},{"name":"rogue-curriculum-builder","version":"2.0.0"},{"name":"rogue-active-deployment","version":"2.0.0"}]}' ;;
  *api.github.com*releases/latest) echo '{"tag_name":"v1.2.1","body":"No changes."}' ;;
  *) exit 1 ;;
esac
